### ISSUE TITLE
同学您好！有个问题想请教一下您

### ISSUE THREAD

**Issue by Kddk-K** [Guest-Liang/BUPT-iOSCalendar-Excel#1]
你好！很感谢你能开源你的项目，以及你的idea。我不是北邮的学生，请问您可以将您的课表也分享一下吗？如果可以我将不胜感激。

**Comment by Guest-Liang** [comment]
好的，这是一个测试文件，我已转换成xlsx格式，记得下载后将文件名重命名为标准格式【学生个人课表_2019123456.xlsx】
[学生个人课表_2019123456.xlsx](https://github.com/Guest-Liang/BUPT-iOSCalendar-Excel/files/11514341/_2019123456.xlsx)

**Comment by Kddk-K** [comment]
十分感谢
